version: '3'
      
services:
  app:
    image: learn-ci
    container_name: memo-app
    ports:
      - 8080:8080
    networks:
      memonet:
        ipv4_address: 10.10.10.2
    depends_on:
      - db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=memo
      - POSTGRES_HOST=db

  db:
    image: postgres:15-alpine
    container_name: memo-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=memo
    networks:
      memonet:
        ipv4_address: 10.10.10.3

networks:
  memonet:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24