version: '3'
      
services:
  db:
    image: postgres:15-alpine
    container_name: memo-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=memo
    networks:
      memonet:
        ipv4_address: 10.10.10.3
  
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: memo-app
    networks:
      memonet:
        ipv4_address: 10.10.10.2
    depends_on:
      - db
    restart: on-failure
    environment:
      - VIRTUAL_HOST=ec2-52-194-210-254.ap-northeast-1.compute.amazonaws.com
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=memo
      - POSTGRES_HOST=db

networks:
  memonet:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24