name: Memo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Unit Tests
        run: go test -v ./service
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
     - name: Install SSH Key
       uses: shimataro/ssh-key-action@v2
       with:
          key: {%- raw -%} ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
     - name: Adding Known Hosts
       run: ssh-keyscan -H ${{ secrets.SSH_HOST }}{% endraw%} >> ~/.ssh/known_hosts